### ISSUE TITLE
[1.15.2] Random Crash on Server - Ticking Entity

### ISSUE THREAD

**Issue by mr-poyo** [Phylogeny/BoundTotems#3]
**Version:** BoundTotems-1.15.2-1.3.0.jar
**Forge:** 31.2.5

Hello,

Had a random server crash while we were playing. None of us have totems so it was kind of weird. One guy says he was fighting hostiles, and I was AFK at my spawn.

Crashlog: https://pastebin.com/zbjL1Pnb
latest.log: https://pastebin.com/LCtX4WAa

At the bottom of the crash log there is a reference to 
 Entity Type: aov:projectilenimbusray (tamaized.aov.common.entity.ProjectileNimbusRay)

Not sure if this is a compatibility, or maybe an issue on AoV's side. Side note, the guy fighting hostiles was using AoV (Angel of vengeance)

Mentioned to AoV dev too just in case. https://github.com/Tamaized/AoV/issues/152

Hope this helps! Thank you!

**Comment by itsfriday19** [comment]
I'm also experiencing this bug, Minecraft 1.15.2 with BoundTotems-1.15.2-1.4.0. I'm using MineColonies, when a colony villager dies (this has happened twice) my game crashes; there are no totems being used. Both times it was an enderman that killed the villager and got the ticking entity error. Both times when I reloaded the game it loaded to a save state a few minutes before the crash.
First [crash log](https://pastebin.com/q7XfqNuB)
Second [crash log](https://pastebin.com/Y7bjxwep)

**Comment by Phylogeny** [comment]
I properly attach `ShelfPositionsProvider` to every `LivingEntity` in `AttachCapabilitiesEvent<Entity>`, and entities' capabilities are in place when `LivingDeathEvent` is called. So passing `ShelfPositionsProvider#CAPABILITY` to `LivingEntity#getCapability` should always return a `ShelfPositions` instance. This is why I call `LazyOptional#orElseThrow` rather than `LazyOptional#ifPresent` on the return value of `LivingEntity#getCapability`.

The bug here is that some mod is somehow preventing instances of `LivingEntity` from having all or any of their normally attached capabilities. The AoV projectile entity in [mr-poyo](https://github.com/mr-poyo)'s crash is just the damage source and thus is irrelevant, and the `LivingEntity` lacking the capability doesn't appear to be from the same mod as the ones in [itsfriday19](https://github.com/itsfriday19)'s crashes.

I have no idea which mod is messing with attached capabilities, but it's definitely not this one. I don't believe it's worth calling `LazyOptional#ifPresent` and thus potentially letting this mod's intended functionally silently fail when another mod inappropriately removes entities' capabilities. I'm closing this as a third-party bug / won't fix.
